### ISSUE TITLE
项目很好加油

### ISSUE THREAD

**Issue by iqovo** [YunYouJun/give-me-money#3]
尝试了克隆项目并运行成功，但修改AppID与key后就失败了
加油吧

**Comment by YunYouJun** [comment]
谢谢，本项目仅作娱乐。
AppID 与 AppKey 为使用的 [LeanCloud](https://www.leancloud.cn/) 开发版应用。

**Comment by iqovo** [comment]
> 谢谢，本项目仅作娱乐。
> AppID 与 AppKey 为使用的 [LeanCloud](https://www.leancloud.cn/) 开发版应用。

我也使用的 LeanCloud 开发版应用，但是修改之后就无法访问了，目前找不到原因

**Comment by YunYouJun** [comment]
@iqovo  您还需在 LeanCloud 中手动新建 `Pay` 与 `Counter` 这两个 Class，其余字段将自动新建。

**Comment by iqovo** [comment]
> Counter
您好项目仍然白页面，但是尝试还原回您的AppID 与 AppKey后正常有些奇怪

**Comment by iqovo** [comment]
> @iqovo 您还需在 LeanCloud 中手动新建 `Pay` 与 `Counter` 这两个 Class，其余字段将自动新建。

您好项目仍然白页面，但是尝试还原回您的AppID 与 AppKey后正常有些奇怪

**Comment by YunYouJun** [comment]
好的，我明天再排查一下，顺便抽取成环境变量。今天实在没有时间。

**Comment by YunYouJun** [comment]
@iqovo Hello，现在已经将 `appId` 和 `appKey` 进行了抽取，可以直接在 `.env` 文件中配置。可参见此处 [Use](https://github.com/YunYouJun/give-me-money#use)。
以及在初始化页面时，若应用中不存在对应类会自动创建。您可以尝试是否可以正常运行，谢谢你的支持。

**Comment by iqovo** [comment]
> @iqovo Hello，现在已经将 `appId` 和 `appKey` 进行了抽取，可以直接在 `.env` 文件中配置。可参见此处 [Use](https://github.com/YunYouJun/give-me-money#use)。
> 以及在初始化页面时，若应用中不存在对应类会自动创建。您可以尝试是否可以正常运行，谢谢你的支持。

已经尝试，并发现 LeanCloud 的用量统计有显示被使用，但并不会自动创建，所以页面仍然是空白。
是node版本问题？
⚠️  Could not load existing sourcemap of "node_modules/vue-about-me/dist/VueAboutMe.umd.min.js".
⚠️  Could not load existing sourcemap of "node_modules/valine/dist/Valine.min.js".

**Comment by YunYouJun** [comment]
能否提供浏览器控制台的提示信息？
我当前使用的是 Node.js LTS `v12.16.1`，但应当与此关联不大。
`soucemap` 的缺失不影响正常使用，在 Parcel 构建完后消息应该会自动消失。

**Comment by YunYouJun** [comment]
国内版 LeanCloud 还需要设置 `serverURL`，所以更推荐使用不需要设置 `serverURL` 的国际版 LeanCloud。
该问题已得到解决，将关闭 ISSUE。
